---
language: go
go:
  - 1.11.x
env:
  - TZ=UTC
jobs:
  include:
    - stage: test
      install:
        - wget -qO - "https://github.com/go-task/task/releases/download/v2.2.1/task_linux_amd64.tar.gz" |
          tar zxf - -C /tmp task;
          ls -la /tmp/task
        - wget -qO - https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > /tmp/codeclimate-test-reporter;
          chmod +x /tmp/codeclimate-test-reporter
        - export PATH=$PATH:/tmp
        - task --version
      script:
        - codeclimate-test-reporter before-build
        - task test
      after_success:
        - codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: release
      install:
        - wget -qO - "https://github.com/go-task/task/releases/download/v2.2.1/task_linux_amd64.tar.gz" |
          tar zxf - -C /tmp task;
          ls -la /tmp/task
        - export PATH=$PATH:/tmp
        - task --version
      script:
        - BINARY_PATH="release/syml" GOOS=linux GOARCH=amd64 task compile
        - ls release/
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: release/syml-linux
        on:
          tags: true  
